from __future__ import annotations

import json
import re

from platform_cli.core.errors import PlatformError

from .models import ReleasePlan

PUBLIC_RUNTIME_DEFAULT_KEYS = (
    "GHDP_DEFAULT_REPO",
    "GHDP_AWS_REGION",
    "GHDP_AWS_SSO_SESSION_NAME",
    "GHDP_AWS_SSO_START_URL",
    "GHDP_AWS_SSO_REGION",
    "GHDP_AWS_DEFAULT_REGION",
    "GHDP_TABLEAU_RELEASE_BASE_URL",
    "GHDP_INSTALL_FLAVOR",
)


def render_release_notes(plan: ReleasePlan) -> str:
    if not plan.summary_file.exists():
        raise PlatformError(
            f"GHDP could not render release notes because the release summary file is missing: {plan.summary_file}. "
            "Create or restore that file, then rerun the release command.",
            code="E_RELEASE_NOTES_MISSING",
            reason="release_notes",
        )

    summary_markdown = _clean_summary(plan.summary_file.read_text(encoding="utf-8"))
    if not summary_markdown.strip():
        raise PlatformError(
            f"GHDP could not render release notes because '{plan.summary_file}' is empty after cleanup. "
            "Add a human-readable release summary to that file, then retry.",
            code="E_RELEASE_NOTES_EMPTY",
            reason="release_notes",
        )

    return f"""## Metadata
- Build source ref: `{plan.source_ref}`
- Install flavor: `{plan.install_flavor}`

## Summary
{summary_markdown}

## Install

### macOS / Linux
```bash
GHDP_TOKEN="<YOUR TOKEN>" \\
GHDP_REPO="{plan.repo_name_with_owner}" \\
GHDP_VERSION="{plan.tag}" \\
bash -c '
  REF="{plan.tag}"
  curl -fsSL \\
    -H "Authorization: token $GHDP_TOKEN" \\
    -H "Accept: application/vnd.github.raw+json" \\
    -H "X-GitHub-Api-Version: 2022-11-28" \\
    -G "https://api.github.com/repos/$GHDP_REPO/contents/platform-cli/install_ghdp.sh" \\
    --data-urlencode "ref=$REF" | bash' && ghdp
```

### Windows (PowerShell admin)
```powershell
$env:GHDP_TOKEN="<YOUR_GITHUB_PAT>";
$repo="{plan.repo_name_with_owner}";
$tag="{plan.tag}";
$asset="ghdp-windows-amd64.exe";
$dir=Join-Path $env:LOCALAPPDATA "ghdp\\bin";
New-Item -ItemType Directory -Force -Path $dir|Out-Null;
$exe=Join-Path $dir "ghdp.exe";
$h=@{{Authorization="token $env:GHDP_TOKEN";"X-GitHub-Api-Version"="2022-11-28"}};
$rel=Invoke-RestMethod -Headers $h -Uri "https://api.github.com/repos/$repo/releases/tags/$tag";
$aid=($rel.assets|?{{$_.name -eq $asset}}).id;
if(-not $aid){{throw "Asset not found"}};
curl.exe -fL -H "Authorization: token $env:GHDP_TOKEN" -H "Accept: application/octet-stream" -H "X-GitHub-Api-Version: 2022-11-28" "https://api.github.com/repos/$repo/releases/assets/$aid" -o "$exe";
$p=[Environment]::GetEnvironmentVariable("Path","User");
if(-not ($p -split ';' | ? {{$_ -eq $dir}})){{[Environment]::SetEnvironmentVariable("Path",(($p.TrimEnd(';')+";"+$dir).Trim(';')),"User")}};
$env:Path="$dir;$env:Path";
& $exe
```

## Verify
```bash
ghdp --help
ghdp --version
```

## Uninstall
### macOS / Linux
```bash
rm -f "$HOME/.local/bin/ghdp"
```

### Windows (PowerShell)
```powershell
$exe = (Get-Command ghdp -ErrorAction SilentlyContinue).Source
if ($exe) {{ Remove-Item -Force $exe; "Removed: $exe" }} else {{ "ghdp not found in PATH" }}
```
"""


def write_build_metadata(plan: ReleasePlan) -> None:
    managed_token = _managed_build_token(plan)
    plan.build_meta_path.parent.mkdir(parents=True, exist_ok=True)
    plan.build_meta_path.write_text(
        "# Auto-generated by GHDP release command.\n"
        f'BUILD_TAG = "{plan.tag}"\n'
        f'BUILD_VERSION = "{plan.build_version}"\n'
        f'BUILD_CHANNEL = "{plan.build_channel}"\n'
        f'BUILD_INSTALL_FLAVOR = "{plan.install_flavor}"\n',
        encoding="utf-8",
    )
    with plan.build_meta_path.open("a", encoding="utf-8") as handle:
        handle.write(f'BUILD_MANAGED_GITHUB_TOKEN = "{managed_token}"\n')


def _managed_build_token(plan: ReleasePlan) -> str:
    if plan.install_flavor != "managed":
        return ""
    token = _managed_bundle_token()
    if token:
        return token
    raise PlatformError(
        "Managed binary build requires GHDP_MANAGED_GITHUB_TOKEN (or GHDP_MANAGED_INSTALL_TOKEN / GHDP_MANAGED_TOKEN).",
        code="E_RELEASE_MANAGED_TOKEN_REQUIRED",
        reason="managed_build_token_missing",
    )


def write_runtime_defaults(plan: ReleasePlan) -> None:
    payload = {key: _runtime_default_value(plan, key) for key in PUBLIC_RUNTIME_DEFAULT_KEYS}
    plan.runtime_defaults_path.parent.mkdir(parents=True, exist_ok=True)
    plan.runtime_defaults_path.write_text(
        "# Auto-generated by GHDP release command.\n"
        "RUNTIME_DEFAULTS = "
        + json.dumps(payload, indent=2, sort_keys=True)
        + "\n",
        encoding="utf-8",
    )


def _clean_summary(raw: str) -> str:
    summary_heading = re.compile(r"^[ \t]{0,3}#{1,6}[ \t]*summary[ \t]*$", re.IGNORECASE)
    summary_label = re.compile(r"^[ \t]*summary[ \t]*:?[ \t]*$", re.IGNORECASE)
    lines = []
    for line in (raw or "").splitlines():
        if summary_heading.match(line) or summary_label.match(line):
            continue
        lines.append(line.rstrip())
    return "\n".join(lines).strip()


def _env_value(key: str) -> str:
    import os

    return str(os.getenv(key, "") or "").strip()


def _runtime_default_value(plan: ReleasePlan, key: str) -> str:
    if key == "GHDP_INSTALL_FLAVOR":
        return plan.install_flavor
    return _env_value(key)


def _managed_bundle_token() -> str:
    for key in (
        "GHDP_MANAGED_GITHUB_TOKEN",
        "GHDP_MANAGED_INSTALL_TOKEN",
        "GHDP_MANAGED_TOKEN",
    ):
        value = _env_value(key)
        if value:
            return value
    return ""


