# NOTE: Architectural rules in ARCHITECTURE.md — do not refactor cross-layer.
from __future__ import annotations

import os

RUNTIME_DEFAULT_KEYS = (
    "GHDP_DEFAULT_REPO",
    "GHDP_AWS_REGION",
    "GHDP_AWS_SSO_SESSION_NAME",
    "GHDP_AWS_SSO_START_URL",
    "GHDP_AWS_SSO_REGION",
    "GHDP_AWS_DEFAULT_REGION",
    "GHDP_TABLEAU_RELEASE_BASE_URL",
    "GHDP_INSTALL_FLAVOR",
)


def load_secure_defaults_into_env() -> int:
    """
    Load build-time injected runtime defaults from the packaged binary/module.

    These defaults are generated by the release workflow from GitHub Actions
    variables/secrets and shipped inside the built artifact. They are not
    persisted into local user files.
    """
    try:
        from platform_cli._runtime_defaults import RUNTIME_DEFAULTS  # type: ignore
    except Exception:
        return 0

    if not isinstance(RUNTIME_DEFAULTS, dict):
        return 0

    loaded = 0
    for key in RUNTIME_DEFAULT_KEYS:
        if key in os.environ:
            continue
        value = (RUNTIME_DEFAULTS.get(key) or "").strip() if isinstance(RUNTIME_DEFAULTS.get(key), str) else RUNTIME_DEFAULTS.get(key)
        if value:
            os.environ[key] = str(value)
            loaded += 1
    return loaded


def bootstrap_secure_defaults_from_file(_path) -> int:
    """
    Legacy no-op retained only so older installer code paths do not crash if
    they still invoke the hidden bootstrap command.
    """
    return 0
